
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                Footer
            </div>
        </div>
    </div>
</footer>


<script src="<?php echo BASE_URL;?>/js/dist/libs.min.js"></script>
<script src="<?php echo BASE_URL;?>/js/dist/functions.min.js"></script>
<script src="<?php echo BASE_URL;?>/js/dist/main.min.js"></script>

<div id="fb-root"></div>

<script>
/*
(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/pt_PT/sdk.js#xfbml=1&version=v2.6&appId=123123123";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));*/

/*(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
e=o.createElement(i);r=o.getElementsByTagName(i)[0];
e.src='//www.google-analytics.com/analytics.js';
r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
ga('create','UA-XXXXX-X','auto');ga('send','pageview');*/
</script>

</body>
</html>
