<!doctype html>
<html lang="<?=$_SESSION['WEBSITE_LANGUAGE']; ?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?=$_SESSION['WEBSITE_HTML_TITLE']; ?></title>
    <meta name="description" content="<?=$_SESSION['WEBSITE_DESCRIPTION']; ?>">
    <meta name="keywords" content="<?=$_SESSION['WEBSITE_KEYWORDS']; ?>">
    <meta name="summary" content="<?=$_SESSION['WEBSITE_DESCRIPTION']; ?>">
    <meta name="subject" content="<?=$_SESSION['WEBSITE_DESCRIPTION']; ?>">
    <meta name="copyright" content="<?=$_SESSION['WEBSITE_NAME']; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="<?=$_SESSION['WEBSITE_AUTHOR_NAME']; ?>, <?=$_SESSION['WEBSITE_AUTHOR_EMAIL']; ?>">
    <meta name="reply-to" content="<?=$_SESSION['WEBSITE_AUTHOR_EMAIL']; ?>">
    <meta name="language" content="<?=$_SESSION['WEBSITE_LANGUAGE']; ?>">
    <meta name="url" content="<?=BASE_URL;?>">
    <meta name="identifier-URL" content="<?=BASE_URL;?>">
    <meta name="coverage" content="Worldwide">
    <meta name="classification" content="Business">
    <meta name="distribution" content="Global">
    <meta name="rating" content="General">
    <meta name="revisit-after" content="4 days">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="<?=$_SESSION['WEBSITE_NAME']; ?>">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="robots" content="noindex, nofollow">

    <meta content="text/html; charset=UTF-8; X-Content-Type-Options=nosniff" http-equiv="Content-Type" />

    <meta name="og:title" content="<?=$_SESSION['WEBSITE_HTML_TITLE']; ?>"/>
    <meta name="og:type" content="website"/>
    <meta name="og:url" content="<?=BASE_URL;?>"/>
    <meta name="og:image" content="<?=COMPANY_LOGO;?>"/>
    <meta name="og:site_name" content="<?=$_SESSION['WEBSITE_NAME']; ?>"/>
    <meta name="og:description" content="<?=$_SESSION['WEBSITE_DESCRIPTION']; ?>"/>
    <meta name="fb:page_id" content="" />
    <meta name="og:email" content=""/>
    <meta name="og:phone_number" content=""/>
    <meta name="og:fax_number" content=""/>
    <meta name="og:latitude" content=""/>
    <meta name="og:longitude" content=""/>
    <meta name="og:street-address" content=""/>
    <meta name="og:locality" content=""/>
    <meta name="og:region" content=""/>
    <meta name="og:postal-code" content=""/>
    <meta name="og:country-name" content=""/>

    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<?=BASE_URL;?>/ms-icon-144x144.png?v=3">
    <meta name="theme-color" content="#ffffff">

    <meta http-equiv="cache-control" content="public">
    <meta http-equiv="expires" content="Sun, 19 Jan 2014 11:12:13 GMT">
    <meta http-equiv="cleartype" content="on">

    <link rel="shortcut icon" type="image/ico" href="<?=BASE_URL;?>/favicon.ico?v=8">
    <link rel="apple-touch-icon" sizes="57x57" href="<?=BASE_URL;?>/apple-icon-57x57.png?v=3">
    <link rel="apple-touch-icon" sizes="60x60" href="<?=BASE_URL;?>/apple-icon-60x60.png?v=3">
    <link rel="apple-touch-icon" sizes="72x72" href="<?=BASE_URL;?>/apple-icon-72x72.png?v=3">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=BASE_URL;?>/apple-icon-76x76.png?v=3">
    <link rel="apple-touch-icon" sizes="114x114" href="<?=BASE_URL;?>/apple-icon-114x114.png?v=3">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=BASE_URL;?>/apple-icon-120x120.png?v=3">
    <link rel="apple-touch-icon" sizes="144x144" href="<?=BASE_URL;?>/apple-icon-144x144.png?v=3">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=BASE_URL;?>/apple-icon-152x152.png?v=3">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=BASE_URL;?>/apple-icon-180x180.png?v=3">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?=BASE_URL;?>/android-icon-192x192.png?v=3">
    <link rel="icon" type="image/png" sizes="32x32" href="<?=BASE_URL;?>/favicon-32x32.png?v=3">
    <link rel="icon" type="image/png" sizes="96x96" href="<?=BASE_URL;?>/favicon-96x96.png?v=3">
    <link rel="icon" type="image/png" sizes="16x16" href="<?=BASE_URL;?>/favicon-16x16.png?v=3">
    <link rel="manifest" href="<?=BASE_URL;?>/manifest.json">

    <link rel="stylesheet" href="<?=BASE_URL;?>/css/dist/libs.min.css">
    <link rel="stylesheet" href="<?=BASE_URL;?>/css/dist/main.min.css">

    <script>
        var BASE_URL     = '<? =BASE_URL;?>';
        var WEBSITE_NAME = '<? =$_SESSION['WEBSITE_NAME']?>';
    </script>

    <script src="<?php echo BASE_URL;?>/js/modernizr-custom.js"></script>
    <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI=" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="<?=BASE_URL;?>/js/libs/jquery/jquery-2.2.2.min.js"><\/script>')</script>

</head>
<body >

    <?php include 'top_bar.phtml'; ?>
