<div class="langs">

    <?php
    $langSelectedPT = false;
    $langSelectedEN = false;

    if ($_SESSION['LANG'] == 'pt') {
        $langSelectedPT = true;
    } elseif ($_SESSION['LANG'] == 'en') {
        $langSelectedEN = true;
    }
    ?>

    <ul>
        <li><a class="<?=$langSelectedPT==true?"active":""?>" href="<?=BASE_URL?>/?lang=pt">PT</a></li>
        <li><a class="<?=$langSelectedEN==true?"active":""?>" href="<?=BASE_URL?>/?lang=en">EN</a></li>
    </ul>

</div>

<div class="menu">
    <?=$data['menuHtmlMain'];?>
</div>
