<!doctype html>
<html lang="<?=$_SESSION['WEBSITE_LANGUAGE'];?>">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?=$_SESSION['WEBSITE_HTML_TITLE']?></title>
    <meta name="description" content="<?=$_SESSION['WEBSITE_DESCRIPTION'];?>">
    <meta name="keywords" content="<?=$_SESSION['WEBSITE_KEYWORDS'];?>">
    <meta name="copyright" content="<?=$_SESSION['COMPANY_NAME'];?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="<?=COMPANY_DEV_NAME?>, <?=COMPANY_DEV_EMAIL?>">
    <meta name="language" content="<?=$_SESSION['LANG'];?>">
    <meta name="url" content="<?=BASE_URL;?>">
    <meta name="identifier-URL" content="<?=BASE_URL;?>">
    <meta name="revisit-after" content="4 days">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="<?=$_SESSION['WEBSITE_NAME'];?>">
    <meta name="apple-touch-fullscreen" content="yes">
    <?php if (WEBSITE_INDEX == "1") { ?>
    <meta name="robots" content="index, follow">
    <?php }else{ ?>
    <meta name="robots" content="noindex, nofollow">
    <?php }?>

    <meta content="text/html; charset=UTF-8; X-Content-Type-Options=nosniff" http-equiv="Content-Type" />

    <meta name="og:title" content="<?=$_SESSION['WEBSITE_NAME'];?>"/>
    <meta name="og:url" content="<?=BASE_URL;?>"/>
    <meta name="og:image" content="<?=COMPANY_LOGO;?>"/>
    <meta name="og:site_name" content="<?=$_SESSION['WEBSITE_NAME'];?>"/>
    <meta name="og:description" content="<?=$_SESSION['WEBSITE_DESCRIPTION'];?>"/>
    <meta name="fb:page_id" content="<?=$_SESSION['WEBSITE_SOCIAL_FB_PAGEID'];?>" />
    <meta name="og:email" content="<?=$_SESSION['COMPANY_EMAIL'];?>"/>
    <meta name="og:phone_number" content="<?=$_SESSION['COMPANY_TELEPHONE'];?>"/>
    <meta name="og:latitude" content="<?=$_SESSION['LOCAL_LATITUDE'];?>"/>
    <meta name="og:longitude" content="<?=$_SESSION['LOCAL_LONGITUDE'];?>"/>
    <meta name="og:street-address" content="<?=$_SESSION['COMPANY_ADDRESS'];?>"/>
    <meta name="og:locality" content="<?=$_SESSION['WEBSITE_SOCIAL_LOCALITY'];?>"/>
    <meta name="og:region" content="<?=$_SESSION['COMPANY_LOCALE'];?>"/>
    <meta name="og:postal-code" content="<?=$_SESSION['COMPANY_POSTAL_CODE'];?>"/>
    <meta name="og:country-name" content="<?=$_SESSION['COMPANY_COUNTRY'];?>"/>

    <meta name="msapplication-TileColor" content="ffffff">
    <meta name="msapplication-TileImage" content="<?=BASE_URL;?>/ms-icon-144x144.png">
    <meta name="theme-color" content="ffffff">

    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="cache-control" content="public">
    <meta http-equiv="expires" content="Sun, 19 Jan 2014 11:12:13 GMT">
    <meta http-equiv="cleartype" content="on">

    <link rel="apple-touch-icon" sizes="57x57" href="<?=BASE_URL;?>/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<?=BASE_URL;?>/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<?=BASE_URL;?>/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<?=BASE_URL;?>/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<?=BASE_URL;?>/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<?=BASE_URL;?>/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<?=BASE_URL;?>/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<?=BASE_URL;?>/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<?=BASE_URL;?>/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="<?=BASE_URL;?>/android-icon-192x192.png">
    <link rel="icon" type="image/ico" href="<?=BASE_URL;?>/favicon.ico?v=14">
    <link rel="manifest" href="<?=BASE_URL;?>/manifest.json">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">

    <link rel="stylesheet" href="<?=BASE_URL;?>/dist/css/libs.min.css">
    <link rel="stylesheet" href="<?=BASE_URL;?>/dist/css/main.min.css">

    <script>
        var BASE_URL       = '<?=BASE_URL;?>';
        var GENERAL_DELAY  = 1000;
        var HTML_SPINNER   = '<i class="fa fa-spinner fa-pulse"></i>';
    </script>

    <script type="text/javascript" src="<?=BASE_URL;?>/dist/js/libs.min.js"></script>
    <script type="text/javascript" src="<?=BASE_URL;?>/dist/js/functions.min.js"></script>
    <script type="text/javascript" src="<?=BASE_URL;?>/dist/js/main.min.js"></script>

</head>
<body>





